services:
  chis-blog:
    container_name: chis-blog
    restart: unless-stopped
    build: .
    ports:
      - "2564:3000"
    env_file:
      - .env
    command: /bin/sh -c "rm -f ./public/sitemap.xml && yarn build && yarn run start"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blog.rule=Host(`chis.dev`)"
      - "traefik.http.routers.blog.entrypoints=websecure"
      - "traefik.http.routers.blog.tls.certresolver=cloudflare"